// Code generated by protoc-gen-go. DO NOT EDIT.
// source: miner/miner.proto

/*
Package miner is a generated protocol buffer package.

It is generated from these files:
	miner/miner.proto

It has these top-level messages:
	PingRequest
	PingReply
	HandshakeRequest
	HandshakeReply
	StartRequest
	StartReply
	StopRequest
	StopReply
	TasksStatusRequest
	TaskStatus
	TasksStatusReply
*/
package miner

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskStatus_Status int32

const (
	TaskStatus_UNKNOWN  TaskStatus_Status = 0
	TaskStatus_SPOOLING TaskStatus_Status = 1
	TaskStatus_SPAWNING TaskStatus_Status = 2
	TaskStatus_RUNNING  TaskStatus_Status = 3
	TaskStatus_FINISHED TaskStatus_Status = 4
	TaskStatus_BROKEN   TaskStatus_Status = 5
)

var TaskStatus_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SPOOLING",
	2: "SPAWNING",
	3: "RUNNING",
	4: "FINISHED",
	5: "BROKEN",
}
var TaskStatus_Status_value = map[string]int32{
	"UNKNOWN":  0,
	"SPOOLING": 1,
	"SPAWNING": 2,
	"RUNNING":  3,
	"FINISHED": 4,
	"BROKEN":   5,
}

func (x TaskStatus_Status) String() string {
	return proto.EnumName(TaskStatus_Status_name, int32(x))
}
func (TaskStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingReply struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type HandshakeRequest struct {
	Hub string `protobuf:"bytes,1,opt,name=hub" json:"hub,omitempty"`
}

func (m *HandshakeRequest) Reset()                    { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string            { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()               {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HandshakeRequest) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}

type HandshakeReply struct {
	Miner string `protobuf:"bytes,1,opt,name=miner" json:"miner,omitempty"`
}

func (m *HandshakeReply) Reset()                    { *m = HandshakeReply{} }
func (m *HandshakeReply) String() string            { return proto.CompactTextString(m) }
func (*HandshakeReply) ProtoMessage()               {}
func (*HandshakeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HandshakeReply) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

type StartRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Registry string `protobuf:"bytes,2,opt,name=registry" json:"registry,omitempty"`
	Image    string `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StartRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StartRequest) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *StartRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type StartReply struct {
	Container string                     `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Ports     map[string]*StartReplyPort `protobuf:"bytes,2,rep,name=Ports,json=ports" json:"Ports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *StartReply) Reset()                    { *m = StartReply{} }
func (m *StartReply) String() string            { return proto.CompactTextString(m) }
func (*StartReply) ProtoMessage()               {}
func (*StartReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StartReply) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *StartReply) GetPorts() map[string]*StartReplyPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

type StartReplyPort struct {
	IP   string `protobuf:"bytes,1,opt,name=IP,json=iP" json:"IP,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
}

func (m *StartReplyPort) Reset()                    { *m = StartReplyPort{} }
func (m *StartReplyPort) String() string            { return proto.CompactTextString(m) }
func (*StartReplyPort) ProtoMessage()               {}
func (*StartReplyPort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *StartReplyPort) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *StartReplyPort) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type StopRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StopReply struct {
}

func (m *StopReply) Reset()                    { *m = StopReply{} }
func (m *StopReply) String() string            { return proto.CompactTextString(m) }
func (*StopReply) ProtoMessage()               {}
func (*StopReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type TasksStatusRequest struct {
}

func (m *TasksStatusRequest) Reset()                    { *m = TasksStatusRequest{} }
func (m *TasksStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*TasksStatusRequest) ProtoMessage()               {}
func (*TasksStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type TaskStatus struct {
	Status TaskStatus_Status `protobuf:"varint,1,opt,name=status,enum=miner.TaskStatus_Status" json:"status,omitempty"`
}

func (m *TaskStatus) Reset()                    { *m = TaskStatus{} }
func (m *TaskStatus) String() string            { return proto.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()               {}
func (*TaskStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TaskStatus) GetStatus() TaskStatus_Status {
	if m != nil {
		return m.Status
	}
	return TaskStatus_UNKNOWN
}

type TasksStatusReply struct {
	Statuses map[string]*TaskStatus `protobuf:"bytes,1,rep,name=statuses" json:"statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TasksStatusReply) Reset()                    { *m = TasksStatusReply{} }
func (m *TasksStatusReply) String() string            { return proto.CompactTextString(m) }
func (*TasksStatusReply) ProtoMessage()               {}
func (*TasksStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TasksStatusReply) GetStatuses() map[string]*TaskStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "miner.PingRequest")
	proto.RegisterType((*PingReply)(nil), "miner.PingReply")
	proto.RegisterType((*HandshakeRequest)(nil), "miner.HandshakeRequest")
	proto.RegisterType((*HandshakeReply)(nil), "miner.HandshakeReply")
	proto.RegisterType((*StartRequest)(nil), "miner.StartRequest")
	proto.RegisterType((*StartReply)(nil), "miner.StartReply")
	proto.RegisterType((*StartReplyPort)(nil), "miner.StartReply.port")
	proto.RegisterType((*StopRequest)(nil), "miner.StopRequest")
	proto.RegisterType((*StopReply)(nil), "miner.StopReply")
	proto.RegisterType((*TasksStatusRequest)(nil), "miner.TasksStatusRequest")
	proto.RegisterType((*TaskStatus)(nil), "miner.TaskStatus")
	proto.RegisterType((*TasksStatusReply)(nil), "miner.TasksStatusReply")
	proto.RegisterEnum("miner.TaskStatus_Status", TaskStatus_Status_name, TaskStatus_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Miner service

type MinerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeReply, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error)
	TasksStatus(ctx context.Context, opts ...grpc.CallOption) (Miner_TasksStatusClient, error)
}

type minerClient struct {
	cc *grpc.ClientConn
}

func NewMinerClient(cc *grpc.ClientConn) MinerClient {
	return &minerClient{cc}
}

func (c *minerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeReply, error) {
	out := new(HandshakeReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Handshake", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error) {
	out := new(StartReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error) {
	out := new(StopReply)
	err := grpc.Invoke(ctx, "/miner.Miner/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minerClient) TasksStatus(ctx context.Context, opts ...grpc.CallOption) (Miner_TasksStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Miner_serviceDesc.Streams[0], c.cc, "/miner.Miner/TasksStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &minerTasksStatusClient{stream}
	return x, nil
}

type Miner_TasksStatusClient interface {
	Send(*TasksStatusRequest) error
	Recv() (*TasksStatusReply, error)
	grpc.ClientStream
}

type minerTasksStatusClient struct {
	grpc.ClientStream
}

func (x *minerTasksStatusClient) Send(m *TasksStatusRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *minerTasksStatusClient) Recv() (*TasksStatusReply, error) {
	m := new(TasksStatusReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Miner service

type MinerServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Handshake(context.Context, *HandshakeRequest) (*HandshakeReply, error)
	Start(context.Context, *StartRequest) (*StartReply, error)
	Stop(context.Context, *StopRequest) (*StopReply, error)
	TasksStatus(Miner_TasksStatusServer) error
}

func RegisterMinerServer(s *grpc.Server, srv MinerServer) {
	s.RegisterService(&_Miner_serviceDesc, srv)
}

func _Miner_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/miner.Miner/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Miner_TasksStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MinerServer).TasksStatus(&minerTasksStatusServer{stream})
}

type Miner_TasksStatusServer interface {
	Send(*TasksStatusReply) error
	Recv() (*TasksStatusRequest, error)
	grpc.ServerStream
}

type minerTasksStatusServer struct {
	grpc.ServerStream
}

func (x *minerTasksStatusServer) Send(m *TasksStatusReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *minerTasksStatusServer) Recv() (*TasksStatusRequest, error) {
	m := new(TasksStatusRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Miner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "miner.Miner",
	HandlerType: (*MinerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Miner_Ping_Handler,
		},
		{
			MethodName: "Handshake",
			Handler:    _Miner_Handshake_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Miner_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Miner_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TasksStatus",
			Handler:       _Miner_TasksStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "miner/miner.proto",
}

func init() { proto.RegisterFile("miner/miner.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0x38, 0x24, 0xe3, 0x36, 0x72, 0x96, 0xd2, 0x06, 0xab, 0x48, 0xd5, 0xf2, 0x15,
	0x21, 0x14, 0x4a, 0xb8, 0x20, 0x24, 0x0e, 0x45, 0x84, 0x36, 0x2a, 0x38, 0x96, 0x4d, 0x55, 0xae,
	0x2e, 0x59, 0xa5, 0x56, 0x52, 0xdb, 0xd8, 0x1b, 0x24, 0xff, 0x13, 0xce, 0x48, 0xfc, 0x2b, 0x7e,
	0x0c, 0x9a, 0xdd, 0x8d, 0x3f, 0x48, 0x7b, 0xb1, 0x76, 0x66, 0xdf, 0x9b, 0x79, 0x9a, 0x37, 0x6b,
	0xe8, 0xdf, 0x84, 0x11, 0x4b, 0x5f, 0x89, 0xef, 0x28, 0x49, 0x63, 0x1e, 0x13, 0x43, 0x04, 0x74,
	0x17, 0x4c, 0x37, 0x8c, 0x16, 0x1e, 0xfb, 0xb1, 0x66, 0x19, 0xa7, 0x8f, 0xa1, 0x2b, 0xc3, 0x64,
	0x95, 0x93, 0x7d, 0x68, 0x67, 0x3c, 0xe0, 0xeb, 0x6c, 0xa0, 0x1d, 0x69, 0xc3, 0xae, 0xa7, 0x22,
	0xfa, 0x04, 0xac, 0xb3, 0x20, 0x9a, 0x67, 0xd7, 0xc1, 0x92, 0x29, 0x22, 0xb1, 0xa0, 0x79, 0xbd,
	0xbe, 0x52, 0x40, 0x3c, 0xd2, 0x67, 0xd0, 0xab, 0xa0, 0xb0, 0xde, 0x1e, 0xc8, 0xa6, 0x0a, 0xa5,
	0x14, 0xb8, 0xb0, 0xe3, 0xf3, 0x20, 0xe5, 0x9b, 0x4a, 0x3d, 0xd0, 0xc3, 0xb9, 0x82, 0xe8, 0xe1,
	0x9c, 0xd8, 0xd0, 0x49, 0xd9, 0x22, 0xcc, 0x78, 0x9a, 0x0f, 0x74, 0x91, 0x2d, 0x62, 0xac, 0x18,
	0xde, 0x04, 0x0b, 0x36, 0x68, 0xca, 0x8a, 0x22, 0xa0, 0x7f, 0x35, 0x00, 0x55, 0x12, 0xdb, 0x1e,
	0x42, 0xf7, 0x7b, 0x1c, 0xf1, 0xa0, 0xd2, 0xba, 0x4c, 0x90, 0x31, 0x18, 0x6e, 0x9c, 0xf2, 0x6c,
	0xa0, 0x1f, 0x35, 0x87, 0xe6, 0xf8, 0x70, 0x24, 0x87, 0x54, 0xf2, 0x47, 0xe2, 0x7a, 0x12, 0xf1,
	0x34, 0xf7, 0x8c, 0x04, 0xcf, 0xf6, 0x0b, 0x68, 0xe1, 0x01, 0xa5, 0x4e, 0xdd, 0x42, 0xaa, 0x4b,
	0x88, 0xcc, 0x2b, 0x99, 0xe2, 0x6c, 0xbb, 0x00, 0x65, 0x01, 0x1c, 0xd3, 0x92, 0xe5, 0x9b, 0x31,
	0x2d, 0x59, 0x4e, 0x5e, 0x82, 0xf1, 0x33, 0x58, 0xad, 0x99, 0x20, 0x99, 0xe3, 0xfd, 0xed, 0xfe,
	0x58, 0xc6, 0x93, 0xa0, 0x77, 0xfa, 0x5b, 0x8d, 0x3e, 0x02, 0xd3, 0xe7, 0x71, 0x72, 0xc7, 0xbc,
	0xa8, 0x09, 0x5d, 0x79, 0x9d, 0xac, 0x72, 0xba, 0x07, 0xe4, 0x6b, 0x90, 0x2d, 0x33, 0x5f, 0x38,
	0xb7, 0x71, 0xf9, 0x97, 0x06, 0x80, 0x69, 0x99, 0x25, 0xc7, 0x35, 0x9f, 0x7b, 0xe3, 0x81, 0xd2,
	0x50, 0x42, 0x46, 0x8a, 0xbf, 0xd9, 0x80, 0x6f, 0xd0, 0x56, 0x5c, 0x13, 0xee, 0x5d, 0x38, 0xe7,
	0xce, 0xec, 0xd2, 0xb1, 0x1a, 0x64, 0x07, 0x3a, 0xbe, 0x3b, 0x9b, 0x7d, 0x9e, 0x3a, 0xa7, 0x96,
	0x26, 0xa3, 0x93, 0x4b, 0x07, 0x23, 0x1d, 0x81, 0xde, 0x85, 0x23, 0x82, 0x26, 0x5e, 0x7d, 0x9a,
	0x3a, 0x53, 0xff, 0x6c, 0xf2, 0xd1, 0x6a, 0x11, 0x80, 0xf6, 0x07, 0x6f, 0x76, 0x3e, 0x71, 0x2c,
	0x83, 0xfe, 0xd1, 0xc0, 0xaa, 0x29, 0x46, 0x07, 0x4f, 0xa0, 0x23, 0x1b, 0x33, 0x94, 0x88, 0x36,
	0x3d, 0xad, 0x48, 0xac, 0x42, 0x95, 0x50, 0xa6, 0xfc, 0x2a, 0x68, 0xb6, 0x03, 0xbb, 0xb5, 0xab,
	0x5b, 0x9c, 0x78, 0x5e, 0x77, 0xa2, 0xbf, 0x35, 0x85, 0x8a, 0x09, 0xe3, 0xdf, 0x3a, 0x18, 0x5f,
	0xc4, 0x02, 0x8d, 0xa0, 0x85, 0x4f, 0x86, 0x10, 0x85, 0xaf, 0x3c, 0x27, 0xdb, 0xaa, 0xe5, 0xd0,
	0x90, 0x06, 0x79, 0x0f, 0xdd, 0xe2, 0x5d, 0x90, 0x03, 0x05, 0xf8, 0xff, 0x3d, 0xd9, 0x0f, 0xb6,
	0x2f, 0x24, 0xfd, 0x35, 0x18, 0x62, 0x37, 0xc8, 0xfd, 0xfa, 0xa6, 0x48, 0x5a, 0x7f, 0x6b, 0x7d,
	0x68, 0x03, 0x15, 0xe2, 0x46, 0x14, 0x0a, 0x2b, 0xdb, 0x53, 0x28, 0x2c, 0x57, 0xa6, 0x41, 0x4e,
	0xc1, 0xac, 0xcc, 0x95, 0x3c, 0xbc, 0x6d, 0xd6, 0x92, 0x7d, 0x70, 0x87, 0x0d, 0xb4, 0x31, 0xd4,
	0x8e, 0xb5, 0xab, 0xb6, 0xf8, 0xd5, 0xbc, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x20, 0xd8, 0x55,
	0x76, 0x7f, 0x04, 0x00, 0x00,
}
