// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub/hub.proto

/*
Package hub is a generated protocol buffer package.

It is generated from these files:
	hub/hub.proto

It has these top-level messages:
	PingRequest
	PingReply
	ListRequest
	ListReply
	StartTaskRequest
	StartTaskReply
	StopTaskRequest
	StopTaskReply
	MinerStatusRequest
	TaskStatusRequest
	TaskStatusReply
*/
package hub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import miner "github.com/sonm-io/core/proto/miner"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingReply struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListReply struct {
	Info map[string]*ListReply_ListValue `protobuf:"bytes,1,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ListReply) Reset()                    { *m = ListReply{} }
func (m *ListReply) String() string            { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()               {}
func (*ListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListReply) GetInfo() map[string]*ListReply_ListValue {
	if m != nil {
		return m.Info
	}
	return nil
}

type ListReply_ListValue struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *ListReply_ListValue) Reset()                    { *m = ListReply_ListValue{} }
func (m *ListReply_ListValue) String() string            { return proto.CompactTextString(m) }
func (*ListReply_ListValue) ProtoMessage()               {}
func (*ListReply_ListValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *ListReply_ListValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type StartTaskRequest struct {
	Miner    string `protobuf:"bytes,1,opt,name=miner" json:"miner,omitempty"`
	Registry string `protobuf:"bytes,2,opt,name=registry" json:"registry,omitempty"`
	Image    string `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
}

func (m *StartTaskRequest) Reset()                    { *m = StartTaskRequest{} }
func (m *StartTaskRequest) String() string            { return proto.CompactTextString(m) }
func (*StartTaskRequest) ProtoMessage()               {}
func (*StartTaskRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StartTaskRequest) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *StartTaskRequest) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *StartTaskRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type StartTaskReply struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Endpoint []string `protobuf:"bytes,2,rep,name=endpoint" json:"endpoint,omitempty"`
}

func (m *StartTaskReply) Reset()                    { *m = StartTaskReply{} }
func (m *StartTaskReply) String() string            { return proto.CompactTextString(m) }
func (*StartTaskReply) ProtoMessage()               {}
func (*StartTaskReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StartTaskReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StartTaskReply) GetEndpoint() []string {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type StopTaskRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *StopTaskRequest) Reset()                    { *m = StopTaskRequest{} }
func (m *StopTaskRequest) String() string            { return proto.CompactTextString(m) }
func (*StopTaskRequest) ProtoMessage()               {}
func (*StopTaskRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StopTaskRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StopTaskReply struct {
}

func (m *StopTaskReply) Reset()                    { *m = StopTaskReply{} }
func (m *StopTaskReply) String() string            { return proto.CompactTextString(m) }
func (*StopTaskReply) ProtoMessage()               {}
func (*StopTaskReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type MinerStatusRequest struct {
	Miner string `protobuf:"bytes,1,opt,name=miner" json:"miner,omitempty"`
}

func (m *MinerStatusRequest) Reset()                    { *m = MinerStatusRequest{} }
func (m *MinerStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*MinerStatusRequest) ProtoMessage()               {}
func (*MinerStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MinerStatusRequest) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

type TaskStatusRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *TaskStatusRequest) Reset()                    { *m = TaskStatusRequest{} }
func (m *TaskStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*TaskStatusRequest) ProtoMessage()               {}
func (*TaskStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TaskStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TaskStatusReply struct {
	Status *miner.TaskStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *TaskStatusReply) Reset()                    { *m = TaskStatusReply{} }
func (m *TaskStatusReply) String() string            { return proto.CompactTextString(m) }
func (*TaskStatusReply) ProtoMessage()               {}
func (*TaskStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TaskStatusReply) GetStatus() *miner.TaskStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "hub.PingRequest")
	proto.RegisterType((*PingReply)(nil), "hub.PingReply")
	proto.RegisterType((*ListRequest)(nil), "hub.ListRequest")
	proto.RegisterType((*ListReply)(nil), "hub.ListReply")
	proto.RegisterType((*ListReply_ListValue)(nil), "hub.ListReply.ListValue")
	proto.RegisterType((*StartTaskRequest)(nil), "hub.StartTaskRequest")
	proto.RegisterType((*StartTaskReply)(nil), "hub.StartTaskReply")
	proto.RegisterType((*StopTaskRequest)(nil), "hub.StopTaskRequest")
	proto.RegisterType((*StopTaskReply)(nil), "hub.StopTaskReply")
	proto.RegisterType((*MinerStatusRequest)(nil), "hub.MinerStatusRequest")
	proto.RegisterType((*TaskStatusRequest)(nil), "hub.TaskStatusRequest")
	proto.RegisterType((*TaskStatusReply)(nil), "hub.TaskStatusReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hub service

type HubClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskReply, error)
	StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskReply, error)
	TaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusReply, error)
	MinerStatus(ctx context.Context, in *MinerStatusRequest, opts ...grpc.CallOption) (*miner.TasksStatusReply, error)
}

type hubClient struct {
	cc *grpc.ClientConn
}

func NewHubClient(cc *grpc.ClientConn) HubClient {
	return &hubClient{cc}
}

func (c *hubClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/hub.Hub/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := grpc.Invoke(ctx, "/hub.Hub/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClient) StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskReply, error) {
	out := new(StartTaskReply)
	err := grpc.Invoke(ctx, "/hub.Hub/StartTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClient) StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskReply, error) {
	out := new(StopTaskReply)
	err := grpc.Invoke(ctx, "/hub.Hub/StopTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClient) TaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusReply, error) {
	out := new(TaskStatusReply)
	err := grpc.Invoke(ctx, "/hub.Hub/TaskStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClient) MinerStatus(ctx context.Context, in *MinerStatusRequest, opts ...grpc.CallOption) (*miner.TasksStatusReply, error) {
	out := new(miner.TasksStatusReply)
	err := grpc.Invoke(ctx, "/hub.Hub/MinerStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hub service

type HubServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
	StartTask(context.Context, *StartTaskRequest) (*StartTaskReply, error)
	StopTask(context.Context, *StopTaskRequest) (*StopTaskReply, error)
	TaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusReply, error)
	MinerStatus(context.Context, *MinerStatusRequest) (*miner.TasksStatusReply, error)
}

func RegisterHubServer(s *grpc.Server, srv HubServer) {
	s.RegisterService(&_Hub_serviceDesc, srv)
}

func _Hub_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Hub/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hub_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Hub/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hub_StartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServer).StartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Hub/StartTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServer).StartTask(ctx, req.(*StartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hub_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Hub/StopTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServer).StopTask(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hub_TaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServer).TaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Hub/TaskStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServer).TaskStatus(ctx, req.(*TaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hub_MinerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServer).MinerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Hub/MinerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServer).MinerStatus(ctx, req.(*MinerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hub.Hub",
	HandlerType: (*HubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Hub_Ping_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Hub_List_Handler,
		},
		{
			MethodName: "StartTask",
			Handler:    _Hub_StartTask_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _Hub_StopTask_Handler,
		},
		{
			MethodName: "TaskStatus",
			Handler:    _Hub_TaskStatus_Handler,
		},
		{
			MethodName: "MinerStatus",
			Handler:    _Hub_MinerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub/hub.proto",
}

func init() { proto.RegisterFile("hub/hub.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0x92, 0x6d, 0x5a, 0x6e, 0xd5, 0x2f, 0x53, 0xb6, 0xc8, 0x4f, 0xc5, 0x7d, 0x19, 0x13,
	0xca, 0xa4, 0x22, 0x21, 0x40, 0x7d, 0xe1, 0x01, 0x09, 0x24, 0x90, 0x20, 0x45, 0x3c, 0xf0, 0x96,
	0xa8, 0x5e, 0x6b, 0xad, 0x4b, 0x42, 0xec, 0x20, 0xe5, 0x67, 0xf1, 0x53, 0xf8, 0x47, 0xe8, 0xda,
	0x5e, 0xea, 0xa4, 0x88, 0x97, 0x2a, 0xe7, 0xfa, 0x9c, 0xfb, 0x75, 0x6e, 0x61, 0xb8, 0xab, 0xb3,
	0xdb, 0x5d, 0x9d, 0xc5, 0x65, 0x55, 0xa8, 0x82, 0x04, 0xbb, 0x3a, 0xa3, 0xd3, 0x07, 0x91, 0xf3,
	0xea, 0x56, 0xff, 0x9a, 0x38, 0x1b, 0xc2, 0xe0, 0x8b, 0xc8, 0xb7, 0x09, 0xff, 0x59, 0x73, 0xa9,
	0xd8, 0x02, 0x42, 0x03, 0xcb, 0x7d, 0x43, 0x2e, 0xe1, 0x5c, 0xaa, 0x54, 0xd5, 0x32, 0xf2, 0xe6,
	0xde, 0x75, 0x98, 0x58, 0x84, 0x9a, 0x4f, 0x42, 0xaa, 0x47, 0xcd, 0x6f, 0x0f, 0x42, 0x83, 0x51,
	0xf4, 0x02, 0x4e, 0x45, 0x7e, 0x57, 0x44, 0xde, 0x3c, 0xb8, 0x1e, 0x2c, 0xa3, 0x18, 0x5b, 0x68,
	0x5f, 0xe3, 0x8f, 0xf9, 0x5d, 0xf1, 0x3e, 0x57, 0x55, 0x93, 0x68, 0x16, 0x5d, 0x18, 0xe9, 0xf7,
	0x74, 0x5f, 0x73, 0xac, 0xf7, 0x0b, 0x3f, 0xa4, 0x16, 0x87, 0x89, 0x45, 0xf4, 0x2b, 0x84, 0xad,
	0x8e, 0x4c, 0x20, 0xb8, 0xe7, 0x8d, 0xed, 0x08, 0x3f, 0x49, 0x0c, 0x67, 0x9a, 0x18, 0xf9, 0x73,
	0xef, 0x1f, 0x25, 0xdb, 0xfc, 0x89, 0xa1, 0xbd, 0xf5, 0x5f, 0x7b, 0xec, 0x07, 0x4c, 0xd6, 0x2a,
	0xad, 0xd4, 0xb7, 0x54, 0xde, 0xdb, 0x39, 0xc8, 0x0c, 0xce, 0xf4, 0x66, 0x6c, 0x6e, 0x03, 0x08,
	0x85, 0x8b, 0x8a, 0x6f, 0x85, 0x54, 0x55, 0xa3, 0x0b, 0x84, 0x49, 0x8b, 0x51, 0x21, 0x1e, 0xd2,
	0x2d, 0x8f, 0x02, 0xa3, 0xd0, 0x80, 0xad, 0x60, 0xe4, 0xe4, 0xc6, 0x9d, 0x8c, 0xc0, 0x17, 0x1b,
	0x9b, 0xd6, 0x17, 0x1b, 0xcc, 0xc9, 0xf3, 0x4d, 0x59, 0x88, 0x5c, 0x45, 0xbe, 0x1e, 0xb5, 0xc5,
	0xec, 0x19, 0x8c, 0xd7, 0xaa, 0x28, 0xdd, 0xc6, 0x7a, 0x72, 0x36, 0x86, 0xe1, 0x81, 0x52, 0xee,
	0x1b, 0x76, 0x03, 0xe4, 0x33, 0x36, 0xbb, 0xd6, 0xfe, 0xfc, 0x77, 0x1e, 0xb6, 0x80, 0x29, 0x0a,
	0xbb, 0xd4, 0x7e, 0x85, 0x15, 0x8c, 0x5d, 0x12, 0xce, 0xf0, 0xbc, 0x73, 0x0c, 0x83, 0xe5, 0x34,
	0x36, 0x67, 0xe4, 0xf0, 0x2c, 0x61, 0xf9, 0xc7, 0x87, 0xe0, 0x43, 0x9d, 0x91, 0x1b, 0x38, 0xc5,
	0x63, 0x22, 0x13, 0xed, 0x88, 0x73, 0x66, 0x74, 0xe4, 0x44, 0x70, 0x80, 0x13, 0xe4, 0xa2, 0x51,
	0x96, 0xeb, 0x9c, 0x97, 0xe5, 0xb6, 0x7e, 0xb2, 0x13, 0xf2, 0x06, 0xc2, 0x76, 0xc1, 0xe4, 0xa9,
	0x7e, 0xee, 0x9b, 0x49, 0x9f, 0xf4, 0xc3, 0x46, 0xfa, 0x0a, 0x2e, 0x1e, 0x57, 0x47, 0x66, 0x96,
	0xd2, 0x59, 0x36, 0x25, 0xbd, 0xa8, 0xd1, 0xad, 0x00, 0x0e, 0x83, 0x92, 0x4b, 0xcd, 0x39, 0x5a,
	0x23, 0x9d, 0x1d, 0xc5, 0x8d, 0xfa, 0x1d, 0x0c, 0x1c, 0x7f, 0xc8, 0x95, 0xa6, 0x1d, 0x3b, 0x46,
	0xaf, 0x9c, 0x9d, 0xca, 0x4e, 0x8a, 0xec, 0x5c, 0xff, 0x5d, 0x5f, 0xfe, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xf9, 0x05, 0x24, 0x7a, 0xd7, 0x03, 0x00, 0x00,
}
